### PR TITLE
aws_setup call for PreLinkData

### PR DESCRIPTION
**Pull request by jmhernan**
@timathomas There are some parts of `HILD_merge.R` that don't seem to be needed to produce the `PreLinkData.csv` file. I commented out for now but .take a look and see if things look okay.  
Also, `bind_rows()` (line #50) doesn't like the `dob` formats that are done before it:
```
hmis.rl <- hmis.rl %>%
 		   mutate(dob=ymd(dob))
```  
So i commented those out as well, prob better to format once you have the whole dataset combined.

### CODE REVIEW

**Comment by arokem** [comment]
Could you please delete the lines that are now commented out?

**Comment by jmhernan** [comment]
@arokem I create the R executable file, so now things run through python with a call like:
```
path2script = '/home/joseh/source/puget/merge/HILD_merge.R'
process = subprocess.call(path2script)
```
You mentioned loading that as a module when we load puget?  If you could guide me a bit, I can figure this out.

**Comment by arokem** [comment]
I think that the way to do this would be to get this file into someplace on the users $PATH. I think that one way to do this would create a folder in puget at top level called "/scripts" or something like that and putting your R script in there. 

Then, in the puget/version.py file, you would add a variable: 

    SCRIPTS = ['scripts/*']

And pass this in the setup file as an argument to the `setup` function by adding it to this dict: https://github.com/uwescience-bmgf-hmis/puget/blob/master/setup.py#L10 as `scripts=SCRIPTS`. 

This way, when `python setup.py install` is called, Python knows to find everything in that folder and put it in a location where it can be executed. Then, your code would simplify to: 

    path2script = 'HILD_merge.R'
    process = subprocess.call(path2script)

**Comment by jmhernan** [comment]
@arokem THANKS! I'm close! I was able to get things working only when I use this in puget/version.py:
```
SCRIPTS = ['scripts/merge_test.R']
```
When I try to use the wildcard I get this error:
```
error: file '/home/joseh/source/puget/scripts/*' does not exist
```
I will continue to look into this.

**Comment by arokem** [comment]
It’s totally fine to hard code the name of the script

**Comment by arokem** [comment]
Which is to say that I have no idea why the wildcard isn’t working

**Comment by jmhernan** [comment]
That's true, but I was hoping that could be the home for the other (at least 2) R scripts we need to source for the data pipeline.

**Comment by jmhernan** [comment]
THANKS @bhazelton!  This works!
```
SCRIPTS = glob.glob('scripts/*')
```

**Comment by arokem** [comment]
Oh yes. Good one!

**Comment by jmhernan** [comment]
@bhazelton and @arokem .  Potential issue with passing arguments through python for R script.  This executable file `HILD_merge_ex.R` can be called from python like this:

```
import os.path as op 
import puget
import subprocess 

# You will need to specify the data paths
local_data_path = op.join(op.expanduser('~'), 'data')
hild_directory = op.join(local_data_path, 'HILD/')
hmis_directory = op.join(local_data_path, 'HMIS/2016/')

# subprocess takes the executable file and some arguments 
args = [hild_directory, hmis_directory]
subprocess.call(['HILD_merge_ex.R'] + args)
```

The potential issue is that in the R file, the `args` is read as an object with strings.  
```
args <- commandArgs(trailingOnly = TRUE)
```
Where `args[1]==hild_directory` and `args[2] == hmis_directory` so the corresponding assignment in R looks like this:
```
hild_dir = args[1]
hmis_dir = args[2]

hmis <- fread(paste0(hmis_dir,"puget_preprocessed.csv")) %>%
		mutate(pid0 = paste("HMIS0_",PersonalID,sep=""))

pha <- fread(paste0(hild_dir,"pha_longitudinal.csv")) %>%
		mutate(pid0 = paste("PHA0_",pid, sep = ""))
```
Should I be worried about these being dependent on the order of the python argument `args = [hild_directory, hmis_directory]`?

**Comment by bhazelton** [comment]
I think it's ok for them to depend on the order. That's like positional arguments in python and since this will all be scripted, we can handle it. Just make sure the documentation is clear.

**Comment by jmhernan** [comment]
@bhazelton ready to merge

**Comment by jmhernan** [comment]
@timathomas could you review the merge code on this? I added you as a reviewer.

**Comment by timathomas** [comment]
Ran clean and fast

**Pull request merged**
