### PR TITLE
Iterative record linkage

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Looks like some other commits adding setup and what-not got convolved into this one. I am not sure why. @bhazelton : any ideas on how this happened?

**Comment by bhazelton** [comment]
ok, that will work. Then I can clean up my master after this is merged in. Sorry about the confusion!

**Comment by arokem** [comment]
Any more comments here?

**Comment by bhazelton** [comment]
Looks good to me.

**Comment by arokem** [comment]
So is it ready to merge?

**Comment by bhazelton** [comment]
I think so. It's not like we can't have more PRs if something comes up.

**Pull request merged**
